name: Update Codewars Stats

on:
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4 

      - name: Configurar Node.js
        uses: actions/setup-node@v4 
        with:
          node-version: 24 

      - name: Ejecutar script de actualización
        run: node update-codewars.js

      - name: Guardar cambios en el repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          # El '|| exit 0' evita que el proceso falle si no hay cambios que subir
          git commit -m "chore: update codewars stats" || exit 0
          git push
